# Generated by Django 4.0.2 on 2022-08-10 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('custom_zone_type', models.CharField(blank=True, max_length=255, null=True)),
                ('zone_type', models.CharField(choices=[('business', 'Business'), ('public', 'Public'), ('school', 'School'), ('family', 'Family'), ('other', 'Other')], default='public', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='zone_default_img.jpg', upload_to='users_zone_pic')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zone_chat_pic')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
                ('zone_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
