# Generated by Django 4.0.2 on 2022-08-10 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first', models.FloatField(blank=True, null=True)),
                ('second', models.FloatField(blank=True, null=True)),
                ('operator', models.CharField(choices=[('add', 'Add'), ('subtract', 'Subtract'), ('multiply', 'Multiply'), ('divide', 'Divide')], default='add', max_length=100)),
                ('result', models.FloatField(blank=True, null=True)),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
